INSERT INTO CURRENCY_EXCHANGE(id,CURRENCY_FROM,CURRENCY_to,CONVERSION_MULTIPLE,ENVIRONMENT)
values(10001,'USD','INR',65,'');
INSERT INTO CURRENCY_EXCHANGE(id,CURRENCY_FROM,CURRENCY_to,CONVERSION_MULTIPLE,ENVIRONMENT)
values(10002,'USD','ENK',15,'');
INSERT INTO CURRENCY_EXCHANGE(id,CURRENCY_FROM,CURRENCY_to,CONVERSION_MULTIPLE,ENVIRONMENT)
values(10003,'USD','BIRR',100,'');
INSERT INTO CURRENCY_EXCHANGE(id,CURRENCY_FROM,CURRENCY_to,CONVERSION_MULTIPLE,ENVIRONMENT)
values(10004,'USD','TRL',270,'');
INSERT INTO CURRENCY_EXCHANGE(id,CURRENCY_FROM,CURRENCY_to,CONVERSION_MULTIPLE,ENVIRONMENT)
values(10005,'USD','CAD',1,'');
